QuanLySach/QuanLySach/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QuanLySach.Models;
using QuanLySach.ViewsModels;

namespace QuanLySach.Controllers
{
   
        public class BooksController : Controller
        {
            private readonly AppDbContext _appDbContext;
            private readonly IWebHostEnvironment _webHostEnvironment;

            public BooksController(AppDbContext appDbContext, IWebHostEnvironment webHostEnvironment)
            {
                _appDbContext = appDbContext;
                _webHostEnvironment = webHostEnvironment;
            }
            public IActionResult Index()
            {
                ViewBag.Message = "Quản lý sách";

                

                var products = _appDbContext.Books.Include(p => p.Category).ToList();

                return View(products);
            }

            public IActionResult Create()
            {
                BooksCreateVM booksVM = new BooksCreateVM()
                {
                    Books = new Books(),
                    CategorySelectList = _appDbContext.Categories.Select(item => new SelectListItem
                    {
                        Text = item.CategoryName,
                        Value = item.Id.ToString()
                    })
                };

                return View(booksVM);
            }

            [HttpPost]
            public IActionResult Create(BooksCreateVM booksCreateVM)
            {            

               
                _appDbContext.Books.Add(booksCreateVM.Books);
                _appDbContext.SaveChanges();

                return RedirectToAction("Index");
            }

          

         
            public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var books = _appDbContext.Books.Find(id);
            if (books == null) return NotFound();

            return View(books);
        }

        [HttpPost]
        public IActionResult DeleteProduct(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var books = _appDbContext.Books.Find(id);
            if (books == null) return NotFound();

            _appDbContext.Books.Remove(books);
            _appDbContext.SaveChanges();

            return RedirectToAction("Index");

        }
    }
}

QuanLySach/QuanLySach/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuanLySach.Models;

namespace QuanLySach.Controllers
{
    public class CategoryController : Controller
    {
        private readonly AppDbContext _appDbContext;
        public CategoryController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> categories = _appDbContext.Categories.Include(p => p.Books);
            return View(categories);
        }
        public IActionResult Create()
        {
           
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _appDbContext.Categories.Add(category);
                _appDbContext.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(category);
        }
       
     

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var category = _appDbContext.Categories.Find(id);
            if (category == null) return NotFound();

            return View(category);
        }

        [HttpPost]
        public IActionResult DeleteCategory(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var category = _appDbContext.Categories.Find(id);
            if (category == null) return NotFound();

            _appDbContext.Categories.Remove(category);
            _appDbContext.SaveChanges();

            return RedirectToAction("Index");

        }
    }
}

QuanLySach/QuanLySach/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="no-js" lang="zxx">
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Tuan Le">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Quản Lý Sách </title>

    <!-- Fontfaces CSS-->
    <link href="~/assetsdash/css/font-face.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="~/assetsdash/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="~/assetsdash/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/assetsdash/css/theme.css" rel="stylesheet" media="all">

</head>
<body class="animsition">
    <div class="page-wrapper">
        <!-- HEADER MOBILE-->
        <header class="header-mobile d-block d-lg-none">
            <div class="header-mobile__bar">
                <div class="container-fluid">
                    <div class="header-mobile-inner">
                        <a class="logo" href="index.html">
                            <img src="images/icon/logo.png" alt="CoolAdmin" />
                        </a>
                        <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <nav class="navbar-mobile">
                <div class="container-fluid">
                    <ul class="navbar-mobile__list list-unstyled">
                        <li>
                            <a asp-controller="Category" asp-action="Index">
                                <i class="fas fa-chart-bar"></i>Category
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Books" asp-action="Index">
                                <i class="fas fa-table"></i>Book
                            </a>
                        </li>
                        


                    </ul>
                </div>
            </nav>
        </header>
        <!-- END HEADER MOBILE-->
        <!-- MENU SIDEBAR-->
        <aside class="menu-sidebar d-none d-lg-block">
            <div class="logo">
                <a href="#">
                    <img src="~/assetsdash/images/icon/logo.png" alt="Cool Admin" />
                </a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">

                        <li>
                            <a asp-controller="Category" asp-action="Index">
                                <i class="fas fa-chart-bar"></i>Category
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Books" asp-action="Index">
                                <i class="fas fa-table"></i>Book
                            </a>
                        </li>
                        



                    </ul>
                </nav>
            </div>
        </aside>
        <!-- END MENU SIDEBAR-->
        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            <header class="header-desktop">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="header-wrap">
                           
                            <div class="header-button">

                                <div class="account-wrap">
                                    <div class="account-item clearfix js-item-menu">
                                        <div class="image">

                                            <img src="~/assetsdash/images/icon/TuanAdmin.jpg" alt="Tuan Le" />
                                        </div>
                                        <div class="content">
                                            <a class="js-acc-btn" href="#">Tuan Le</a>
                                        </div>
                                        <div class="account-dropdown js-dropdown">
                                            <div class="info clearfix">
                                                <div class="image">
                                                    <a href="#">
                                                        <img src="~/assetsdash/images/icon/TuanAdmin.jpg" alt="Tuan Le" />
                                                    </a>
                                                </div>
                                                <div class="content">
                                                    <h5 class="name">
                                                        <a href="#">Tuan Le</a>
                                                    </h5>
                                                    <span class="email">levantuanpxu@gmail.com</span>
                                                </div>
                                            </div>
                                            <!--   <div class="account-dropdown__body">
                                                   <div class="account-dropdown__item">
                                                   <a href="#">
                                                   <i class="zmdi zmdi-account"></i>Account
                                                   </a>
                                                   </div>
                                                    </div>
                                            -->
                                            <div class="account-dropdown__footer">
                                                <a asp-controller="Home" asp-action="Books">
                                                    <i class="zmdi zmdi-power"></i>Logout
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </header>

            <!-- HEADER DESKTOP-->


            <div class="main-content">
                <div class="container-fluid">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>




            <!-- Jquery JS-->
            <script src="~/assetsdash/vendor/jquery-3.2.1.min.js"></script>
            <!-- Bootstrap JS-->
            <script src="~/assetsdash/vendor/bootstrap-4.1/popper.min.js"></script>
            <script src="~/assetsdash/vendor/bootstrap-4.1/bootstrap.min.js"></script>
            <!-- Vendor JS       -->
            <script src="~/assetsdash/vendor/slick/slick.min.js">
            </script>
            <script src="~/assetsdash/vendor/wow/wow.min.js"></script>
            <script src="~/assetsdash/vendor/animsition/animsition.min.js"></script>
            <script src="~/assetsdash/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
            </script>
            <script src="~/assetsdash/vendor/counter-up/jquery.waypoints.min.js"></script>
            <script src="~/assetsdash/vendor/counter-up/jquery.counterup.min.js">
            </script>
            <script src="~/assetsdash/vendor/circle-progress/circle-progress.min.js"></script>
            <script src="~/assetsdash/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
            <script src="~/assetsdash/vendor/chartjs/Chart.bundle.min.js"></script>
            <script src="~/assetsdash/vendor/select2/select2.min.js">
            </script>

            <!-- Main JS-->
            <script src="~/assetsdash/js/main.js"></script>


            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            @RenderSection("ScriptsValidate", required: false)
</body>
</html>